# Generated by Django 3.1.3 on 2020-12-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0003_auto_20201124_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heartbeat',
            old_name='datum',
            new_name='datum_utc',
        ),
    ]
