# Generated by Django 3.1.3 on 2020-12-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0004_auto_20201201_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartbeat',
            name='lizenzschluessel',
            field=models.TextField(default='123123asdqwqw', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='software_version',
            field=models.CharField(default='1.0', max_length=10),
            preserve_default=False,
        ),
    ]
