# Generated by Django 3.1.2 on 2021-01-06 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0006_auto_20201208_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heartbeat',
            name='software_version',
        ),
    ]
