# Generated by Django 3.1.3 on 2020-11-19 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandant', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KundeHatSoftware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.CharField(max_length=50)),
                ('version', models.CharField(default='NULL', max_length=10)),
                ('beschreibung', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Standort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('telNr', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('strasse', models.CharField(max_length=100)),
                ('hausnr', models.CharField(max_length=5)),
                ('plz', models.CharField(max_length=10)),
                ('ort', models.CharField(max_length=50)),
                ('kunde_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.kunde')),
            ],
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.software')),
            ],
        ),
        migrations.CreateModel(
            name='Lizenz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(max_length=300)),
                ('detail', models.TextField()),
                ('datum_von', models.DateField(blank=True)),
                ('datum_bis', models.DateField(blank=True)),
                ('KundeHatSoftware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.kundehatsoftware')),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.modul')),
            ],
        ),
        migrations.AddField(
            model_name='kundehatsoftware',
            name='standort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.standort'),
        ),
        migrations.AddField(
            model_name='kundehatsoftware',
            name='swId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.software'),
        ),
    ]
