# Generated by Django 3.1.2 on 2020-10-23 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kundehatsoftware',
            name='lizenz',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kunde',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.kundehatsoftware'),
        ),
    ]
