# Generated by Django 3.1.2 on 2021-01-06 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201201_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kundenlizenz',
            fields=[
                ('lizenz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.lizenz')),
            ],
            bases=('pages.lizenz',),
        ),
        migrations.CreateModel(
            name='Standortlizenz',
            fields=[
                ('lizenz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.lizenz')),
            ],
            bases=('pages.lizenz',),
        ),
    ]
