# Generated by Django 3.1.3 on 2020-11-19 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201120_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standort',
            old_name='kunde_ID',
            new_name='kunde',
        ),
    ]
