# Generated by Django 3.1.2 on 2020-10-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201023_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kunde',
            name='software',
        ),
    ]
