# Generated by Django 3.1.2 on 2020-10-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_kunde_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='version',
            field=models.CharField(default='NULL', max_length=10),
        ),
    ]
