# Generated by Django 3.1.3 on 2020-11-19 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201120_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lizenz',
            old_name='datum_bis',
            new_name='gültig_bis',
        ),
        migrations.RenameField(
            model_name='lizenz',
            old_name='datum_von',
            new_name='gültig_von',
        ),
    ]
