# Generated by Django 3.1.3 on 2020-11-20 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201120_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ansprechpartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('telefon_nr', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('standort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.standort')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kundenbetreuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('telefon_nr', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zuständigkeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ansprechpartner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.ansprechpartner')),
                ('software', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.software')),
            ],
        ),
        migrations.AddField(
            model_name='ansprechpartner',
            name='zuständige_software',
            field=models.ManyToManyField(blank=True, null=True, through='pages.Zuständigkeit', to='pages.Software'),
        ),
    ]
