# Generated by Django 3.1.2 on 2020-10-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_software_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='beschreibung',
            field=models.TextField(default=''),
        ),
    ]
