# Generated by Django 3.1.3 on 2020-11-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20201120_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansprechpartner',
            name='zuständige_software',
            field=models.ManyToManyField(to='pages.Software'),
        ),
        migrations.DeleteModel(
            name='Zuständigkeit',
        ),
    ]
