# Generated by Django 3.1.3 on 2020-11-24 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20201124_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zuständigkeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ansprechpartner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.ansprechpartner')),
                ('software', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.software')),
            ],
        ),
        migrations.AlterField(
            model_name='ansprechpartner',
            name='zuständige_software',
            field=models.ManyToManyField(through='pages.Zuständigkeit', to='pages.Software'),
        ),
    ]
