# Generated by Django 3.1.3 on 2020-11-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=15)),
                ('datum', models.DateTimeField()),
                ('datei_pfad', models.CharField(max_length=300)),
            ],
        ),
    ]
